### ISSUE TITLE
gyp ERR! UNCAUGHT EXCEPTION [...] gyp ERR! This is a bug in `node-gyp`.

### ISSUE THREAD

**Issue by anaelleltd** [Swader/polkadash#22]
This happens when I run the "yarn" command from polkadash folder.

I am on:
Win 10
Node 16.2.0
Yarn 1.22.5

C:\laragon\www\polkadash (master)
λ yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
[-/6] ⢀ waiting...
[-/6] ⢀ waiting...
[6/6] ⢀ node-sass
[4/6] ⢀ yorkie
error C:\laragon\www\polkadash\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\laragon\www\polkadash\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\laragon\www\polkadash\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\laragon\\www\\polkadash\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Program Files (x86)\Python36-32\Scripts" in the PATH
gyp verb `which` failed Error: not found: C:\Program Files (x86)\Python36-32\Scripts
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\polkadash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\polkadash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\polkadash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
gyp verb `which` failed  C:\Program Files (x86)\Python36-32\Scripts Error: not found: C:\Program Files (x86)\Python36-32\Scripts
gyp verb `which` failed     at getNotFoundError (C:\laragon\www\polkadash\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\laragon\www\polkadash\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\laragon\www\polkadash\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\laragon\www\polkadash\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "C:\Program Files (x86)\Python36-32\Scripts". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 16.1.0
gyp verb command install [ '16.1.0' ]
gyp verb install input version string "16.1.0"
gyp verb install installing version: 16.1.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.1.0
gyp verb build dir attempting to create "build" dir: C:\laragon\www\polkadash\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\laragon\www\polkadash\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\laragon\www\polkadash\node_modules\node-sass\build\config.gypi
(node:6292) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp verb config.gypi checking for gypi file: C:\laragon\www\polkadash\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\laragon\www\polkadash\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\laragon\\www\\polkadash\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\laragon\\www\\polkadash\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\laragon\\www\\polkadash\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\atale\\.node-gyp\\16.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\atale\\.node-gyp\\16.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\laragon\\www\\polkadash\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\atale\\.node-gyp\\16.1.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\laragon\\www\\polkadash\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\laragon\\www\\polkadash\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\atale\.node-gyp\16.1.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\laragon\\www\\polkadash\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\laragon\www\polkadash\node_modules\node-sass
gyp ERR! node -v v16.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.

[polkadash error yarn.txt](https://github.com/Swader/polkadash/files/6568440/polkadash.error.yarn.txt)

**Comment by Swader** [comment]
Hi, this is quite out of date - needs a `yarn upgrade` across the board, but node-gyp is problematic on Windows machine, always has been, nothing much we can do to help here other than recommend using WSL2 if you're on Windows.

**Comment by anaelleltd** [comment]
Thanks. I will try WSL2.

**Comment by anaelleltd** [comment]
Workarounds for node-gyp on Windows that worked for me:

1. Install build tools globally: 
> npm install --global windows-build-tools
or
> yarn global add windows-build-tools

2. Set python path manually: 
> npm config set python c:\python27amd64\python.exe

3. Set msbuild path manually: 
> npm config set msbuild_path = "C:\Program Files(x86)\Microsoft Visual Studio\2019\BuildTools" msvs_version = "2019"
