### ISSUE TITLE
Not able to serve, missing README tip ;)

### ISSUE THREAD

**Issue by NukeManDan** [Swader/polkadash#9]
I cloned and did a:

```
yarn install
yarn serve
```

and get this error:
```
 ERROR  Failed to compile with 2 errors                                                                       6:58:26 PM

This dependency was not found:

* @/config in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Dashboard.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @/config


This relative module was not found:

* ./config.js in ./src/connection.js
```

---

After a few minuets digging, of course I found this: https://dotleap.com/polkadash-a-vuejs-dashboard-starter-kit-for-your-substrate-chain/

IMHO the instructions there to **MOVE** the `example.config.js -> config.js` (copying to the correct name still errors out) should appear in the README to help dummies like me get started without digging into support docs :pray:

**Comment by Swader** [comment]
But it is in the README already?

**Comment by NukeManDan** [comment]
yes I see it now 🤦🏼 
Thanks!
